In [1]:
import numpy as np

In [ ]:
#What is NumPy? 
#NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object and tools for working with these arrays. 
#It is the fundamental package for scientific computing with Python. It is open-source software. It contains various features including these important ones:

#A powerful N-dimensional array object
#Sophisticated (broadcasting) functions
#Tools for integrating C/C++ and Fortran code
#Useful linear algebra, Fourier transform, and random number capabilities

In [2]:
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )

In [3]:
# Printing type of arr object
print("Array is of type: ", type(arr))

Array is of type:  <class 'numpy.ndarray'>


In [4]:
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

No. of dimensions:  2


In [5]:
# Printing shape of array
print("Shape of array: ", arr.shape)

Shape of array:  (2, 3)


In [6]:
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

Size of array:  6


In [7]:
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array stores elements of type:  int32


# NumPy Array Creation
There are various ways of Numpy array creation in Python. They are as follows:

For example, you can create an array from a regular Python list or tuple using the array() function. 

The type of the resulting array is deduced from the type of the elements in the sequences.

Often, the element ts of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. 
These minimize the necessity of growing arrays, an expensive operation. 
For example: np.zeros, np.ones, np.full, np.empty, etc.

To create sequences of numbers, NumPy provides a function analogous to the range that returns arrays instead of lists.

arange: returns evenly spaced values within a given interval. step size is specified.

linspace: returns evenly spaced values within a given interval. num no. of elements is returned.

Reshaping array: We can use reshape method to reshape an array. Consider an array with shape (a1, a2, a3, …, aN). We can reshape and convert it into another array with shape (b1, b2, b3, …, bM). The only required condition is a1 x a2 x a3 … x aN = b1 x b2 x b3 … x bM. (i.e. the original size of the array remains unchanged.)

Flatten array: We can use flatten method to get a copy of the array collapsed into one dimension. It accepts order argument. The default value is ‘C’ (for row-major order). Use ‘F’ for column-major order.

In [8]:
# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [9]:
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)


Array created using passed tuple:
 [1 3 2]


In [10]:
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print (d)


An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [12]:
# Create an array with random values
e = np.random.random((2, 2))
print ("\nA random array:\n", e)


A random array:
 [[0.60083644 0.80758725]
 [0.48899596 0.80024742]]


In [13]:
# Create a sequence of integers
# from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print ("\nA sequential array with steps of 5:\n", f)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [14]:
# Create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print ("\nA sequential array with 10 values between"
                                        "0 and 5:\n", g)


A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [15]:
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
 
newarr = arr.reshape(2, 2, 3)
 
print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [16]:
# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
 
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)


Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


In [21]:
# basic operations on single array
import numpy as np
 
a = np.array([1, 2, 5, 3])

In [22]:
# add 1 to every element
print ("Adding 1 to every element:", a+1)

Adding 1 to every element: [2 3 6 4]


In [23]:
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)

Subtracting 3 from each element: [-2 -1  2  0]


In [24]:
# square each element
print ("Squaring each element:", a**2)

Squaring each element: [ 1  4 25  9]


In [25]:
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
 
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)


Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [26]:
a = np.array([[1, 2],
            [3, 4]])
b = np.array([[4, 3],
            [2, 1]])
 
# add arrays
print ("Array sum:\n", a + b)
 
# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)
 
# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]
